version: '3.1'

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=admin
      - MYSQL_DATABASE=bender
    volumes:
      - ./data:/var/lib/mysql
    #network_mode: host

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: admindb
    restart: always
    environment:
     # - MYSQL_ROOT_PASSWORD=mypass
      - PMA_HOST=db #nombre del servicio
     # - PMA_USER=root
     # - PMA_PASSWORD=pass
    depends_on:
      - db
    #network_mode: host

  app:
    container_name: fastapi
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    #network_mode: host
