on: push
name: deploy in docker
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push docker
      run: docker network create my_net && docker-compose up -d --build
      working-directory: dannys_dinner
