name: Deploy on Docker
on:
  pull_request:
  push:
    branches: master
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: create network "my_net"
      run: docker network create my_net
    - name: build compose
      run: docker-compose up -d --build
      working-directory: dannys_dinner
