on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push docker
      uses: docker/build-push-action@v1
      run: docker-compose up -d --build
      working-directory: dannys_dinner
      with:
        username: ${{ secrets.USERNAME  }}
        password: ${{ secrets.PASSWORD  }}
        repository: ${{ github.repository  }}   
